In [9]:
#import dependenceis
import matplotlib.pyplot as plt
import pandas as pd
import scipy.stats as st
import numpy as np

In [15]:
#view data sources
ILI_data_path = 'FluViewPhase2Data (2)/ILINet.csv'
clin_data_path = 'FluViewPhase2Data (2)/WHO_NREVSS_Clinical_Labs.csv'
#pub_data_path = 'FluViewPhase2Data (2)/WHO_NREVSS_Public_Health_Labs.csv'

#read data sources
ILI_data = pd.read_csv(ILI_data_path, skiprows = 1)
clin_data = pd.read_csv(clin_data_path)
#pub_data = pd.read_csv(pub_data_path)

In [59]:
#view ILI
ILI_df = pd.DataFrame(ILI_data)

#remove null values in full columns
ILI_drop = ILI_df.drop(columns = ['% WEIGHTED ILI','AGE 0-4','AGE 25-49', 'AGE 25-64', 'AGE 5-24', 'AGE 50-64','AGE 65'])

#remove any rows that contain X
ILI_drop2 = ILI_drop[ILI_drop['%UNWEIGHTED ILI'] != 'X']
ILI_drop2 = ILI_drop[ILI_drop['NUM. OF PROVIDERS'] != 'X']
ILI_drop2 = ILI_drop[ILI_drop['ILITOTAL'] != 'X']
#ILI_drop2 = ILI-drop[ILI_drop['TOTAL PATIENTS'] != 'X']


#convert datatypes of columns to float
ILI_drop2 = ILI_drop2[['YEAR', 'WEEK', '%UNWEIGHTED ILI', 'ILITOTAL','NUM. OF PROVIDERS','TOTAL PATIENTS']].astype(float)


#clean ILI
clean_ILI = ILI_drop2

clean_ILI

,YEAR,WEEK,%UNWEIGHTED ILI,ILITOTAL,NUM. OF PROVIDERS,TOTAL PATIENTS
0,2016.0,40.0,2.223980,169.0,23.0,7599.0
1,2016.0,40.0,0.940228,14.0,6.0,1489.0
2,2016.0,40.0,1.234420,309.0,49.0,25032.0
3,2016.0,40.0,0.917431,40.0,13.0,4360.0
4,2016.0,40.0,1.252880,668.0,129.0,53317.0
...,...,...,...,...,...,...
11278,2020.0,39.0,0.992833,169.0,34.0,17022.0
11279,2020.0,39.0,1.195460,20.0,6.0,1673.0
11281,2020.0,39.0,4.747600,79.0,6.0,1664.0
11282,2020.0,39.0,0.000000,0.0,1.0,238.0
11283,2020.0,39.0,0.846627,648.0,67.0,76539.0

In [12]:
#view clinical
clin_df = pd.DataFrame(clin_data)

clin_df.head(10)

#clean clinical

                                                                                                      *Beginning for the 2015-16 season, reports from public health and clinical laboratories are presented separately in the weekly influenza update, FluView. Data from clinical laboratories include the weekly total number of specimens tested, the number of positive influenza test, and the percent positive by influenza type.
REGION TYPE REGION               YEAR WEEK TOTAL SPECIMENS TOTAL A TOTAL B PERCENT POSITIVE PERCENT A                                          PERCENT B
States      Alabama              2016 40   406             4       1       1.23             0.99                                                    0.25
            Alaska               2016 40   X               X       X       X                X                                                          X
            Arizona              2016 40   133             0       0       0                0                                                          0
            Arkansas             2016 40   47              0       0       0                0                                                          0
            California           2016 40   668             2       0       0.3              0.3                                                        0
            Colorado             2016 40   260             0       0       0                0                                                          0
            Connecticut          2016 40   199             3       0       1.51             1.51                                                       0
            Delaware             2016 40   40              0       0       0                0                                                          0
            District of Columbia 2016 40   X               X       X       X                X                                                          X

In [23]:
#view public
#pub_df = pd.DataFrame(pub_data)

#pub_df.head(10)

#clean public

In [ ]:
#Combine the cleaned data into a single dataset

#mouse_study = pd.DataFrame.merge(mouse_metadata, study_results, how="inner", on="Mouse ID")